### PR TITLE
All http verbs

### PR DESCRIPTION
**Pull request by nahime0**
This PR introduces the remaining http verbs:

- DELETE
- HEAD
- OPTIONS
- PATCH
- PUT

I've left the PR as a draft for now.

### CODE REVIEW

**Comment by nahime0** [comment]
@nunomaduro a quick question: can I add the python "mock" server I use to test the requests in the repository? 
In case, please suggest a folder where I can put the python file and the documentation on how to run it for local testing.

**Comment by nunomaduro** [comment]
@nahime0 Yes you can. You decide where to put it. Thanks!

**Comment by nahime0** [comment]
> @nahime0 Yes you can. You decide where to put it. Thanks!

Thanks, I'll make a different PR for that

**Comment by nunomaduro** [comment]
Can you PR docs for this PR?

**Comment by nahime0** [comment]
Yes, working on it

**Comment by nahime0** [comment]
PR ready: https://github.com/pestphp/docs/pull/246

**Pull request merged**
